# Generated by Django 2.2.24 on 2021-11-18 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=256)),
                ('input_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_input_type_id', to='question.InputType')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionoption_option_id', to='question.Option')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionoption_question_id', to='question.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=256)),
                ('question_option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_question_option_id', to='question.QuestionOption')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
